contract added for buyer
tavisca-sgogawale/OnlineRetailPortal pull request #1
Opened 2019-10-11 10:45 UTC by tavisca-sgogawale

2019-10-11 11:08 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-details/response.json5
> +        "title": "I-Phone 11s",
can we say this as "name" of the product?

2019-10-11 11:08 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-details/response.json5
> +        "date": "dd-mm-yy"
date format generally followed is UTC :"yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffz"

2019-10-11 11:08 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-details/response.json5
> +        "heroImages": "imageUrl" ,
if its going to be a url of image then it should be something like "www.example.com/imageName"

2019-10-11 11:08 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-details/response.json5
> +        "heroImages": "imageUrl" ,
also heroImage is single entity, so "heroImage"

2019-10-11 11:08 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-details/response.json5
> +        "images":["url1","url2","url3"],
same url comment as above

2019-10-11 11:08 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-details/response.json5
> +//Error response object
make another json response for error

2019-10-11 11:08 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-list/response.json5
> +      "postDate": "dd-mm-yy",
above date format

2019-10-11 11:26 UTC, achirametavisca commented on ApiContract/buyer/ad-details/request.json5
> +
sessionid/auth token is required for every request after login

2019-10-11 11:27 UTC, achirametavisca commented on ApiContract/buyer/ad-details/request.json5
> +//GET /api/products/{productId}
In seller contract URL is /api/advertisement
Both should use either advertisement or product

2019-10-11 11:37 UTC, Swinal-Tavisca requested changes

2019-10-11 11:37 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-details/response.json5
> +{
usually error format followed is 
{
  "code": "402",
  "message": "error message",
  "info": [
    {
      "code": "402",
      "message": "error message"
    }
  ]
}

2019-10-11 11:37 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-list/response.json5
> +      "title": "I-Phone 11s",
can say it as product "name"

2019-10-11 11:37 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-list/response.json5
> +      "heroImage": "www.xyz.com",
www.xyz.com/imageName

2019-10-11 11:37 UTC, Swinal-Tavisca commented on ApiContract/buyer/ad-list/response.json5
> +//Error response object
make another json response for error

2019-10-11 11:37 UTC, Swinal-Tavisca commented on ApiContract/buyer/error-response-forall-apis.json5
> +   "message": "Page not found ",
is clossing braces missing "}" ?

2019-10-12 15:05 UTC, Tavisca-smohite requested changes
I see duplciate files in the PR .
Please remove the files which are not needed.
couple of comments applicable to all files : 
1. add versioning for the apis.
2. come up with the rough list of apis so that giving the url names (and structuring them will be easier)
3. you can refer the rest-api naming conventions https://restfulapi.net/resource-naming/
4. make sure all apis are consistent.
5. Now two cents on few of the apis we are planning to include as of now : 
 - **get all products / advertisements(paginated and/or sorted)** : why are we planning to use the constraint of user id in the request as api demands a list of sorted products irrespective of users.?
- **get a product/ad details** : if url says `api/v1.0/e-business/products/{product-id}` (just an example for versioning) , mandating user-id doesn't make a sense .
 Let's say i am not a user who has posted this ad, and requests the information . then what api is going to do with the information of who asked for this information ? (where session id is already mandatory and we will keep it in logs)
- **another api for sell product or advertisement** : here mandating user id makes sense as we need to tag the product with who wants to sell this.
- **if there is one more api which asks for all products or ads I have posted** then couple of ways to frame the api : 1. `api/v1.0/{api-name or project-name}/user/{user-id}/products (or advertisements)`
           2. `api/v1.0/{api-name or project-name}/products (or advertisements)` => here you can take the user id as mandatory in request (to specify i want products of this particular user).

But problem with the second approach is how you will differentiate between the api : `.../products` which returns all products irrespective or user and one where `..../products` and user id mandatory in request which says get me products of this user ??

2019-10-12 15:05 UTC, Tavisca-smohite commented on ApiContract/buyer/ad-list/request.json5
> +//GET /api/products/{pageno}
how are we trying to fetch the products on main page ?
user id constraint is not applicable here.
Also the query parameters will be a right choice here 
and the format for that is `api/products?pagenumber=1&pagesize=50`

2019-10-12 15:05 UTC, Tavisca-smohite commented on ApiContract/buyer/ad-list/response.json5
> +  "Page":
````c#
"pagingInfo":{
"number" :1,
"size":50,
"totalProducts":5000
}
````

2019-10-12 15:05 UTC, Tavisca-smohite commented on ApiContract/buyer/ad-list/response.json5
> +  "Page":
you can use any other name for `totalProducts` if you want.
return number of total products or total number pages .
`maxNumber` is not giving clear picture of what are you trying to return here

2019-10-15 15:51 UTC, Tavisca-smohite commented on Contracts/v1.0/buyer/ad-details/response.json5
> +            "image":{
What is the use of seller.image?

2019-10-15 15:51 UTC, Tavisca-smohite commented on Contracts/v1.0/buyer/ad-details/response.json5
> +        "purchaseDate": "yyyy'-'MM'-'dd",
What if the product is not for resale ?
Are we not considering those type of products .? Cause if we are then mandating purchasedate doesn’t make sense

2019-10-16 04:52 UTC, achirametavisca requested changes

2019-10-16 04:52 UTC, achirametavisca commented on Contracts/v1.0/buyer/ad-details/response.json5
> +        /[Mandatory] status of the product i.e. Active/Disable/Sold
For comment use //

2019-10-16 04:52 UTC, achirametavisca commented on Contracts/v1.0/buyer/ad-details/response.json5
> +        "purchaseDate": "yyyy'-'MM'-'dd",
Agree. 
Can be optional

2019-10-16 04:52 UTC, achirametavisca commented on Contracts/v1.0/buyer/ad-details/response.json5
> +    "product":
Response object is itself product

2019-10-16 04:52 UTC, achirametavisca commented on Contracts/v1.0/buyer/ad-details/response.json5
> +            "image":{
This is used to show seller image on ad list page as per UI design

2019-10-16 06:02 UTC, Swinal-Tavisca requested changes

2019-10-16 06:02 UTC, Swinal-Tavisca commented on Contracts/v1.0/buyer/ad-details/error-response.json5
> +    "code": "404",
why do we need multiple error response ? if so we need it can we make it as an array of error response?

2019-10-16 06:02 UTC, Swinal-Tavisca commented on Contracts/v1.0/buyer/ad-list/error-response.json5
> +   "code": "404",
again why are multiple error responses required?

2019-10-21 12:14 UTC, achirametavisca approved these changes

2019-10-21 13:16 UTC, Tavisca-smohite approved these changes

2019-10-21 13:18 UTC, Swinal-Tavisca approved these changes

2019-10-21 13:19 UTC, merged