controller support and mock data added with tests
tavisca-sgogawale/OnlineRetailPortal pull request #3
Opened 2019-10-15 03:18 UTC by tavisca-sgogawale

2019-10-15 05:54 UTC, tavisca-snikam requested changes

2019-10-15 05:54 UTC, tavisca-snikam commented on Contracts/buyer/ad-list/response.json5
> +  "products": [
This shouls be ads instead of products. we are dealing with ads

2019-10-15 05:54 UTC, tavisca-snikam commented on Contracts/buyer/ad-list/response.json5
> +      "category": "mobile",
is seller going to put ad under any category. if yes this should be an identifier of category not the complete text

2019-10-15 05:54 UTC, tavisca-snikam commented on Contracts/buyer/ad-list/response.json5
> +      "purchaseDate": "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffz",
We should consider such info as additional info. Lets another example of bike. it may have Km, cc, color, etc details.

2019-10-15 05:54 UTC, tavisca-snikam commented on Contracts/buyer/ad-list/response.json5
> +    "number":"2",
please rename it to page or pageNumber

2019-10-15 05:54 UTC, tavisca-snikam commented on Contracts/buyer/ad-list/response.json5
> +    "size":"50",
please rename it to pageSize

2019-10-15 05:54 UTC, tavisca-snikam commented on Contracts/buyer/ad-list/response.json5
> +    "totalPages":"20"
this should be calculated on browser, it should not be a part of response

2019-10-15 05:54 UTC, tavisca-snikam commented on Contracts/buyer/ad-list/response.json5
> +    "totalPages":"20"
calculation should be done as pages = total records/pageSize +(totalrecords%pageSize>0?1:0)

2019-10-15 07:37 UTC, tavisca-sgogawale commented on Contracts/buyer/ad-list/response.json5
> +    "totalPages":"20"
Contracts are defined in  "apicontract" branch there is another pr for contracts

2019-10-21 12:16 UTC, achirametavisca commented on Contracts/buyer/ad-list/response.json5
> +    "number":"2",
we are already in pagingInfo hence number is fine

2019-10-21 12:16 UTC, achirametavisca commented on Contracts/buyer/ad-list/response.json5
> +    "size":"50",
we are already in pagingInfo hence size is fine

2019-11-01 07:02 UTC, closed without merging