Added catergories contract
tavisca-sgogawale/OnlineRetailPortal pull request #4
Opened 2019-10-15 10:54 UTC by tavisca-vnagaraju

2019-10-15 10:59 UTC, Tavisca-smohite requested changes

2019-10-15 10:59 UTC, Tavisca-smohite commented on Contracts/categories/v1.0/get-categories/error-response.json5
> +{
Make it consistent with other apis

2019-10-21 12:22 UTC, achirametavisca approved these changes

2019-10-22 08:55 UTC, tavisca-vnagaraju commented on Contracts/categories/v1.0/get-categories/error-response.json5
> +{
done

2019-10-22 10:14 UTC, Tavisca-smohite approved these changes

2019-10-24 08:21 UTC, merged