Fixed price field
tavisca-sgogawale/OnlineRetailPortal pull request #41
Opened 2019-11-20 09:15 UTC by tavisca-acharpe

2019-11-20 10:23 UTC, tavisca-cpadole approved these changes
Looks Good

2019-11-20 10:36 UTC, tavisca-mrathore approved these changes
looks good.

2019-11-25 04:28 UTC, Tavisca-smohite requested changes

2019-11-25 04:28 UTC, Tavisca-smohite commented on src/OnlineRetailPortal.Web/Validations/AddProductRequestValidator.cs
> +            RuleFor(x => x.Price.Amount)
should have non-negative check

2019-11-25 04:28 UTC, Tavisca-smohite commented on src/OnlineRetailPortal.Web/Validations/UpdateProductRequestValidator.cs
> +            RuleFor(x => x.Price.Amount)
same as above

2019-11-25 04:36 UTC, tavisca-acharpe commented on src/OnlineRetailPortal.Web/Validations/AddProductRequestValidator.cs
> +            RuleFor(x => x.Price.Amount)
done

2019-11-25 04:36 UTC, tavisca-acharpe commented on src/OnlineRetailPortal.Web/Validations/UpdateProductRequestValidator.cs
> +            RuleFor(x => x.Price.Amount)
done

2019-11-25 04:45 UTC, Tavisca-smohite approved these changes

2019-11-25 04:45 UTC, merged